- name: Prepare servers for deployment
  hosts: all
  vars_files:
    - group_vars/webservers.yml
    - group_vars/secrets.yml

  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags: setup

    - name: Install pip via Galaxy role
      ansible.builtin.import_role:
        name: geerlingguy.pip
      tags: setup

    - name: Install docker pip module
      ansible.builtin.pip:
        name: docker
        state: present
      tags: setup

    - name: Install Docker via Galaxy role
      ansible.builtin.import_role:
        name: geerlingguy.docker
      tags: setup

    - name: Verify Docker installation
      ansible.builtin.command: docker --version
      register: docker_check
      failed_when: docker_check.rc != 0
      changed_when: false
      tags: setup

- name: Deploy Redmine
  hosts: all
  become: true
  vars_files:
    - group_vars/webservers.yml
    - group_vars/secrets.yml

  tasks:
    - name: Ensure Redmine directory exists
      file:
        path: "/opt/redmine"
        state: directory
        mode: '0755'
      tags: redmine

    - name: Create .env file from template
      ansible.builtin.template:
        src: templates/redmine.env.j2
        dest: "/opt/redmine/.env"
        mode: '0640'
      tags: redmine

    - name: Pull redmine Docker image
      community.docker.docker_image:
        name: redmine:latest
        source: pull
        force_source: yes
      tags: redmine

    - name: Run Redmine container
      community.docker.docker_container:
        name: redmine
        image: redmine:latest
        restart_policy: unless-stopped
        ports:
          - "{{ redmine_port }}:3000"
        env_file: "/opt/redmine/.env"
        volumes:
          - "/opt/redmine/files:/usr/src/redmine/files"
        state: started
        detach: true
      tags: redmine
